// AUTOGENERATED: DO NOT EDIT!

package router

var routerSchema = `{
  "description": "Last modified: 12/12/2016",
  "required": ["routes"],
  "properties": {
    "routes": { "$ref": "#/definitions/routes" }
  },
  "definitions": {
    "routes": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[^%\\${}]+$": { "$ref": "#/definitions/rule" }
      }
    },
    "rule": {
      "title": "Rule",
      "type": "object",
      "required": ["matchers", "output"],
      "additionalProperties": false,
      "properties": {
        "matchers": { "$ref": "#/definitions/matchers" },
        "output": { "$ref": "#/definitions/output" }
      }
    },
    "matchers": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^[^%\\${}]+$": { "$ref": "#/definitions/flatValueArr" }
      }
    },
    "output": {
      "type": "object",
      "oneOf": [
        { "$ref": "#/definitions/metricsOutput" },
        { "$ref": "#/definitions/alertsOutput" },
        { "$ref": "#/definitions/analyticsOutput" },
        { "$ref": "#/definitions/notificationsOutput" }
      ]
    },
    "metricsOutput": {
      "title": "Metrics Output",
      "type": "object",
      "additionalProperties": false,
      "required": ["type", "series", "dimensions"],
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^metrics$"
        },
        "series": { "$ref": "#/definitions/envVarSubstValue" },
        "dimensions": { "$ref": "#/definitions/flatValueArr" },
        "value": { "$ref": "#/definitions/flatValue" }
      }
    },
    "alertsOutput": {
      "type": "object",
      "additionalProperties": false,
      "required": ["type", "series", "dimensions", "stat_type"],
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^alerts$"
        },
        "series": { "$ref": "#/definitions/envVarSubstValue" },
        "dimensions": { "$ref": "#/definitions/flatValueArr" },
        "value": { "$ref": "#/definitions/flatValue" },
        "stat_type": {
          "type": "string",
          "enum": ["counter", "gauge"]
        }
      }
    },
    "analyticsOutput": {
      "type": "object",
      "additionalProperties": false,
      "required": ["type", "series"],
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^analytics$"
        },
        "series": { "$ref": "#/definitions/envVarSubstValue" }
      }
    },
    "notificationsOutput": {
      "type": "object",
      "additionalProperties": false,
      "required": ["type", "channel", "icon", "message", "user"],
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^notifications$"
        },
        "channel": { "$ref": "#/definitions/envVarSubstValue" },
        "icon": { "$ref": "#/definitions/envVarSubstValue" },
        "message": { "$ref": "#/definitions/kvSubstValue" },
        "user": { "$ref": "#/definitions/envVarSubstValue" }
      }
    },
    "flatValue": {
      "type": "string",
      "pattern": "^[^%\\${}]+$"
    },
    "flatValueArr": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": { "$ref": "#/definitions/flatValue" }
    },
    "envVarSubstValue": {
      "type": "string",
      "pattern": "^([^\\$%{}]|\\${[^%\\${}]+})+$"
    },
    "kvSubstValue": {
      "type": "string",
      "pattern": "^([^\\$%{}]|\\${[^%\\${}]+}|%{[^%\\${}]+})+$"
    }
  }
}}`
